layout_spectrum: 0.7039322
typography_spectrum: 0.5698518
color:
  saturation: 0.3087145
  lightness: 0.4223992
  brandStrength: 0.9765034
  rhythmicContrast: 0.3420617
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: Treig Pronschinske
